name: Update Parent Repo

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout child repo
        uses: actions/checkout@v3

      - name: Checkout parent repo
        run: |
          git clone --depth=1 --recurse-submodules --shallow-submodules https://github.com/gokulnathan66/Music_recommender_Project_Parent.git parent-repo
          cd parent-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
      - name: Update submodule reference
        run: |
          cd parent-repo
          git submodule update --remote 
          git add .
          git commit -m "Auto-updated submodules to latest commit" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
