name: Update Parent Repo

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout child repo
        uses: actions/checkout@v3

      - name: Checkout parent repo with SSH
        run: |
          git clone --depth=1 --recurse-submodules --shallow-submodules https://github.com/gokulnathan66/Music_recommender_Project_Parent.git parent-repo
          cd parent-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Use SSH key for authentication
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "$DEPLOY_KEY"
          cd parent-repo
          git push origin main
