name: Update Parent Repo

on:
  push:
    branches:
      - main

jobs:
  update-parent:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to push updates
    steps:
      - name: Checkout parent repo with submodules
        uses: actions/checkout@v3
        with:
          repository: gokulnathan66/Music_recommender_Project_Parent
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 1

      - name: Update submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "Auto-updated submodules to latest commit" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main || echo "No changes to push"
